In [17]:
#task 1

i1 = int(input("Enter you first number:"))
i2 = int(input("Enter you second number:"))
i3 = int(input("Enter you third number:"))
i4 = int(input("Enter you fourth number:"))

#r1 = (i1, i2, i3, i4)

task_1 = open("Numbers.txt", "w")

task_1.write(str(i1))
task_1.write("\n")
task_1.write(str(i2))
task_1.write("\n")
task_1.write(str(i3))
task_1.write("\n")
task_1.write(str(i4))

task_1.close()



In [21]:
#task 2
g1 = int(input("Enter your percentage mark:"))

if g1 >= 70:
    print("Your grade is a 1st")
    
elif g1 >= 60:
    print("Your grade is a 2:1")

elif g1 >= 50:
    print("Your grade is a 2:2")
    
elif g1 >= 40:
    print("Your grade is a 3rd")
    
else:
    print("Your grade is a fail")
    
# I am really confused about the extension to task 2...
# In the first line it's said to use both grade and mark, but later said the strings should be grade and grade compared
# Also, at this point I am not sure if we're even going by UK's University grading standards or just grades 1-10???

Your grade is a fail


In [22]:
import numpy as np

In [59]:
#task np 1
array = np.arange(0,10)

print(array)

[0 1 2 3 4 5 6 7 8 9]


In [81]:
#2
wow = np.array([1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=bool)

newwow = wow.reshape(3, 3)

print(newwow)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [89]:
#3
woof = np.arange(1,10,2)

print(woof)

[1 3 5 7 9]


In [91]:
#4 (I found this online but have no idea how it works)
q = np.arange(1,10) 

#q = np.array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]) 
 
odd_values = (q%2 == 1)
 
q[odd_values] = -1 

print(q)

[-1  2 -1  4 -1  6 -1  8 -1]


In [94]:
#5
y = np.arange(1,9)

newy = y.reshape(2, 4)

print(newy)

[[1 2 3 4]
 [5 6 7 8]]


In [106]:
#6 ???
al = np.arange(1,10).reshape(9, 1)
bl = np.arange(1,10).reshape(9, 1)
cl = np.dot(a, b)

print(al)
print(bl)
print(cl)

total_sum = np.sum(c)
print(total_sum)

ValueError: shapes (9,1) and (9,1) not aligned: 1 (dim 1) != 9 (dim 0)