In [4]:
# Set up TensorFlow
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.9.1


In [5]:
# Load a dataset
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11490434/11490434 [==============================] - 1s 0us/step


In [6]:
# Build a machine learning model
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [7]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.03494207, -0.552555  ,  0.02953565,  0.28891367, -0.4292048 ,
         0.78638136, -0.50802004, -0.92228854, -0.4052331 ,  0.7182176 ]],
      dtype=float32)

In [8]:
tf.nn.softmax(predictions).numpy()

array([[0.09825656, 0.05460279, 0.09772678, 0.12666598, 0.06177107,
        0.20830874, 0.05708948, 0.03772607, 0.06326972, 0.19458276]],
      dtype=float32)

In [9]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [10]:
loss_fn(y_train[:1], predictions).numpy()

1.5687339

In [11]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [12]:
# Train and evaluate your model
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 2s 890us/step - loss: 0.2980 - accuracy: 0.9136
Epoch 2/5
1875/1875 [==============================] - 2s 833us/step - loss: 0.1427 - accuracy: 0.9562
Epoch 3/5
1875/1875 [==============================] - 2s 853us/step - loss: 0.1075 - accuracy: 0.9674
Epoch 4/5
1875/1875 [==============================] - 2s 835us/step - loss: 0.0897 - accuracy: 0.9716
Epoch 5/5
1875/1875 [==============================] - 2s 820us/step - loss: 0.0760 - accuracy: 0.9765


In [13]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - loss: 0.0759 - accuracy: 0.9762 - 279ms/epoch - 892us/step


[0.07592297345399857, 0.9761999845504761]

In [14]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [15]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[3.2100214e-08, 9.5434745e-09, 5.5875385e-06, 1.2357392e-03,
        5.2904646e-11, 8.5156650e-08, 2.7927099e-12, 9.9874473e-01,
        7.7132768e-07, 1.2984778e-05],
       [6.1171118e-10, 3.3918556e-03, 9.9638152e-01, 2.2561492e-04,
        2.9486565e-14, 9.2359602e-07, 2.7496752e-08, 9.3709649e-12,
        1.4884656e-08, 4.1847062e-13],
       [1.7404967e-07, 9.9910456e-01, 2.4743215e-04, 6.4372662e-06,
        6.9784228e-06, 5.6262393e-06, 5.9074600e-06, 6.0187868e-04,
        2.0961630e-05, 1.0889185e-07],
       [9.9974829e-01, 3.9379209e-08, 9.4387478e-06, 3.1165162e-06,
        9.5082228e-08, 1.8100884e-05, 1.8388237e-04, 7.0007891e-06,
        2.5783436e-08, 3.0009211e-05],
       [2.2531469e-07, 1.1859816e-09, 3.4048785e-06, 4.9906298e-08,
        9.9933004e-01, 1.9564023e-08, 2.2000316e-07, 5.4253328e-06,
        1.8264298e-07, 6.6044967e-04]], dtype=float32)>